TestWebAPI/Models/ErrorViewModel.cs
namespace TestWebAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestWebAPI/Controllers/CalInterestMonthController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace TestWebAPI.Controllers
{
    public class CalInterestMonthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CalInterest(int months, long moneyFirst, double rateMonths)
        {
            if (months <= 0 || moneyFirst <= 0 || rateMonths <= 0)
                ViewData["result"] = "Invalid input. Please provide positive values.";

            else
            {
                string requestUrl = @$"https://localhost:7126/api/Cau1/CalculateCompoundInterest?months={months}&moneyFirst={moneyFirst}&rateMonths={rateMonths}";

                HttpClient client = new HttpClient();
                var response = client.GetStringAsync(requestUrl).Result;
                ViewData["result"] = response;
            }
            return View();
        }
    }
}

TestWebAPI/Controllers/CheckPrimeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWebAPI.Controllers
{
    public class CheckPrimeController : Controller
    {
        public IActionResult Index(string listNumbers)
        {
            if (listNumbers==null)
            {
                ViewData["result"] = "chưa nhập giá trị";
            }
            else
            {
                string[] numbers = listNumbers.Split(" ");

                string requestUrl = @$"https://localhost:7126/api/Cau3/CheckPrimeNumbers?";
                foreach (var item in numbers)
                {
                    requestUrl += $"numbers={item}&";
                }

                HttpClient client = new HttpClient();
                var response = client.GetStringAsync(requestUrl).Result;
                ViewData["result"] = response;

            }
            return View();
        }
    }
}

TestWebAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestWebAPI.Models;

namespace TestWebAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWebAPI/Controllers/PhuongTrinhBac2Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace TestWebAPI.Controllers
{
    public class PhuongTrinhBac2Controller : Controller
    {
        public IActionResult SolveTheX(double a, double b, double c)
        {
            double discriminant = b * b - 4 * a * c;
            if (a == 0 && b == 0 && c == 0)
                ViewData["result"] = "Phương trình vô số nghiệm";
            else if (discriminant < 0)
                ViewData["result"] = "Phương trình vô nghiệm";
            else
            {
                string requestUrl = @$"https://localhost:7126/api/Cau2/SolveQuadraticEquation?a={a}&b={b}&c={c}";

                HttpClient client = new HttpClient();
                var response = client.GetStringAsync(requestUrl).Result;
                ViewData["result"] = response;
            }

            return View();
        }

    }
}

TestWebAPI/Views/CalInterestMonth/CalInterest.cshtml
@{
    ViewData["Title"] = "Nhập 3 giá trị";
}

<h2>@ViewData["Title"]</h2>

<form method="post">
    <label for="months">Số tháng:</label>
    <input type="number" id="months" name="months"><br>

    <label for="moneyFirst">Số tiền:</label>
    <input type="number" id="moneyFirst" name="moneyFirst"><br>

    <label for="rateMonths">Tỉ lệ lãi hàng tháng (%):</label>
    <input type="number" id="rateMonths" step="any" name="rateMonths"><br>

    <button type="submit">Tính lãi </button>

</form>
<h2>@ViewData["result"]</h2>

TestWebAPI/Views/CheckPrime/Index.cshtml
@{
    ViewData["Title"] = "Nhập 3 giá trị";
}

<h2>@ViewData["Title"]</h2>

<form method="post">
    

    <label for="listNumbers">Nhập chuỗi số (có space):</label>
    <input type="text" id="listNumbers" name="listNumbers"><br>

    <button type="submit">kiểm tra </button>

</form>
<h2>@ViewData["result"]</h2>

TestWebAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestWebAPI/Views/PhuongTrinhBac2/SolveTheX.cshtml
@{
    ViewData["Title"] = "Nhập 3 giá trị a b c";
}

<h2>@ViewData["Title"]</h2>

<form method="post">
    <label for="a">Hệ số a:</label>
    <input type="number" step="any" id="a" name="a"><br>

    <label for="b">Hệ số b:</label>
    <input type="number" step="any" id="b" name="b"><br>

    <label for="c">Hệ số c:</label>
    <input type="number"step="any" id="c"  name="c"><br>

    <button type="submit">Tính nghiệm:  </button>

</form>
<h2>@ViewData["result"]</h2>

TestWebAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWebAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestWebAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalInterestMonth" asp-action="CalInterest">Tính lãi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhuongTrinhBac2" asp-action="SolveTheX">Tính Phương Trình</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckPrime" asp-action="Index">Kiểm tra nguyên tố</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestWebAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>